create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text check (char_length(display_name) <= 80),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.entitlements (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users (id) on delete cascade,
  product_key text not null default 'speedread_lifetime',
  status text not null default 'inactive' check (status in ('inactive', 'active', 'refunded', 'revoked')),
  source text,
  source_payment_id text unique,
  granted_at timestamptz,
  updated_at timestamptz not null default now()
);

create index entitlements_user_id_idx on public.entitlements (user_id);

create table public.reading_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  words_read integer not null check (words_read between 1 and 1000000),
  reading_wpm integer not null check (reading_wpm between 100 and 1200),
  baseline_wpm integer not null default 240 check (baseline_wpm between 100 and 600),
  seconds_spent integer not null check (seconds_spent between 1 and 86400),
  minutes_saved numeric(12, 2) generated always as (
    greatest(0, words_read::numeric / baseline_wpm - words_read::numeric / reading_wpm)
  ) stored,
  completed_at timestamptz not null default now()
);

create index reading_sessions_user_id_completed_at_idx
  on public.reading_sessions (user_id, completed_at desc);

create table public.platform_totals (
  singleton boolean primary key default true check (singleton),
  words_read bigint not null default 0 check (words_read >= 0),
  minutes_saved numeric(14, 2) not null default 0 check (minutes_saved >= 0),
  sessions_completed bigint not null default 0 check (sessions_completed >= 0),
  active_readers bigint not null default 0 check (active_readers >= 0),
  refreshed_at timestamptz not null default now()
);

insert into public.platform_totals (singleton) values (true)
on conflict (singleton) do nothing;

alter table public.profiles enable row level security;
alter table public.entitlements enable row level security;
alter table public.reading_sessions enable row level security;
alter table public.platform_totals enable row level security;

create policy "profiles_select_own"
  on public.profiles for select to authenticated
  using ((select auth.uid()) = id);

create policy "profiles_update_own"
  on public.profiles for update to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

create policy "entitlements_select_own"
  on public.entitlements for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "reading_sessions_select_own"
  on public.reading_sessions for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "reading_sessions_insert_own"
  on public.reading_sessions for insert to authenticated
  with check ((select auth.uid()) = user_id);

create policy "platform_totals_public_read"
  on public.platform_totals for select to anon, authenticated
  using (true);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1)));

  insert into public.entitlements (user_id)
  values (new.id)
  on conflict (user_id) do nothing;

  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.refresh_platform_totals()
returns public.platform_totals
language plpgsql
security definer set search_path = ''
as $$
declare
  refreshed public.platform_totals;
begin
  insert into public.platform_totals (
    singleton,
    words_read,
    minutes_saved,
    sessions_completed,
    active_readers,
    refreshed_at
  )
  select
    true,
    coalesce(sum(words_read), 0)::bigint,
    coalesce(sum(minutes_saved), 0)::numeric(14, 2),
    count(*)::bigint,
    count(distinct user_id)::bigint,
    now()
  from public.reading_sessions
  on conflict (singleton) do update set
    words_read = excluded.words_read,
    minutes_saved = excluded.minutes_saved,
    sessions_completed = excluded.sessions_completed,
    active_readers = excluded.active_readers,
    refreshed_at = excluded.refreshed_at
  returning * into refreshed;

  return refreshed;
end;
$$;

revoke all on function public.refresh_platform_totals() from public, anon, authenticated;
grant execute on function public.refresh_platform_totals() to service_role;

grant select, update on public.profiles to authenticated;
grant select on public.entitlements to authenticated;
grant select, insert on public.reading_sessions to authenticated;
grant select on public.platform_totals to anon, authenticated;

